version: '3.9'

services:
    app:
        build: .
        container_name: dash_app
        expose:
            - 8050
        restart: always

    nginx:
        image: nginx:1.25-alpine
        container_name: nginx_proxy
        ports:
            - '8050:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        restart: always
